name: CICD - Main
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    uses: vineethbandlamudi/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'nodejs'
